### ISSUE TITLE
Reflection returns uncatched fatal exception on implementation from type instead interface

### ISSUE THREAD

**Issue by adevyatov** [railt/railt#115]
- Railt Version: dev-master
- PHP Version: 7.1
- Component: SDL

### Description:
Trying to implement type from another type return FatalThrowableError)

### Steps To Reproduce:
Create two types
Implement one type from other, e.g.:
```graphql
type ApiResponse {
    success: Boolean!
}

type LoginResponse implements ApiResponse {
    token: String!
    success: Boolean!
}
```

### Expected result:
Return cathed exception

### What happens instead?
Return fatal exception

**Comment by SerafimArts** [comment]
Fixed: https://github.com/railt/railt/commit/3e93d5642e3ba28c94af8a8d912e6d05e4b522ae
