### ISSUE TITLE
Routing improvements

### ISSUE THREAD

**Issue by SerafimArts** [railt/railt#16]
Divide the routing component into two component parts:
- Routing
- Decorators

## Routing

The route must return complete data for the response, including all available relations. 

### Definitions

The following methods should be implemented:

- `->query('name', '...')`: Must respond to query requests.
- `->mutation('name', '...')`: Must respond to mutation requests.
- `->subscription('name', '...')`: Must respond to subscription requests.
- `->on('name', '...')`: Must respond to all requests.

The second argument is a router handler (`callable` or string definition `ClassName@action`).

The action should provide complete information about the:
- Relations
- Arguments
- Field type
- ...other

**Example:**

```graphql
schema {
    query: Query
}

type Query {
    users: [User]!
}

type User {
    id: ID!
    name: String!
    friends: [User]!
    createdAt: DateTime!
}
```

```php
$router->query('users', function (Input $input) {
    $query = new DatabaseBuilder();

    if ($input->hasRelation('friends')) {
        $query->leftJoin(...);
    }
    
    return $query->get();
});
```

## Decorators

The decorators system should provide the ability to manage and format already generated data. A class must implement at least three methods:

### Middleware

Definition `->middleware('name', '...')`. The first argument contains the name and group of the middlevare, the second is the response handler. The nesting group is separated by a "dot" (`.`) symbol. To use this decoration system - it must be declared in routs explicitly.

**Example:**

```php
// Definition
$decorators->middleware('example', function ($input, $output) { ... });

// Usage the "example" middleware
$router->on('users', function (...) { ... })->middleware('example');
```

**Example with groups:**
```php
// Definition
$decorators->middleware('group-example.test1', function ($input, $output) { ... });
$decorators->middleware('group-example.test2', function ($input, $output) { ... });
$decorators->middleware('group-example', function ($input, $output) { ... });

// Usage of "group-example", "group-example.test1" and "group-example.test2" middleware
$router->on('users', function (...) { ... })->middleware('group-example'); 
```

### Path

The definition of "path decorators" should point explicitly to the field in the query inheritance chain (the collection indexes should not be taken into account when compiling the path).

**Example**
```php
// Processing the field "createdAt" for the GraphQL query: "{ users { friends { createdAt } }"
$decorators->path('users.friends.createdAt', function (...) { ... });
```

### Type-hint

"Type-hint" decorators must respond to the type matching in the declaration and the return result (using the `instanceof` operator).

**Example:**

```php
// Processing the all fields which return a type that is one of the `DateTimeInterface` children.
$decorator->type(\DateTimeInterface::class, function (...) { ... });
```

**Comment by stenin-nikita** [comment]
I think it's better to determine the routes for type and field

### Example

```php
Buffer::setLoader(function(array $ids) {
    $query = new DatabaseBuilder();
    $query->whereIn('id', $ids);

    return $query->get();
});

$router->query('Query.users', function (Input $input) {
    $query = new DatabaseBuilder();

    return $query->get();
});

// Example of solving the problem N + 1
$router->query('User.friends', function ($root, Input $input) {
    Buffer::add($root->id);

    return new Deffered(function () use ($root) {
        Buffer::load();

        return Buffer::get($root->id);
    });
});

$router->query('User.email', function ($root, Input $input) {
    return Str::lower($root->email);
});

$router->query('User.{field}|{type}.expiredAt', 'Controller@action')
    ->where('type', 'AuthUser')
    ->where('field', 'createAt|updatedAt');

$router->query('*.foo', function ($root, Input $input) {
    return 'bar';
});
```

To solve the problem N + 1, we need to come up with another API for the buffer

**Comment by SerafimArts** [comment]
@stenin-nikita maybe it's just an extra possibility for the router? Well. Do not choose one of, but implement both "examples"

**Comment by stenin-nikita** [comment]
### Example router based on directives

```graphql
# The inside of the router

enum InvocationBehaviour {
    Auto,                # Automatically, depending on the availability of the relationship
    OneCallPerParent,    # Calling the method with the transfer of all parent data
    OneCallPerItem       # Behavior in Webonyx and Youshido
}

input Relation { parent: String!, child: String! }

directive @route(action: String!, logic: InvocationBehaviour = Auto, join: Relation) on FIELD

# User code

type Query {
    users: [User]
        @route(action: "UserController@getUsers")
}

type Message {
    id: ID!
    body: String!
}

type User {
    id: ID!
    name: String!
    messages(orderBy: String! = "id"): [Message]
        @route(action: "MessageController@getMessages", join: {parent: "id", child: "author_id"})
}
```

### Example of solving the problem N+1

```php
public function getMessages(Collection $users, Input $input)
{
    return Message::whereIn($users->map->id)
        ->orderBy($input->get('orderBy'))
        ->get(); // Collection {[ Message { id, body, author_id }, Message { id, body, author_id } ]}
}
```

**Comment by SerafimArts** [comment]
The basic implementation of the idea is completed and implemented. It remains to write tests +)
