### ISSUE TITLE
Class 'Railt\Compiler\Parser\Runtime' not found

### ISSUE THREAD

**Issue by talbergs** [railt/railt#169]
- Railt Version: dev-master
- PHP Version: 7.1
- Parser

### Description:
```swift
Fatal error: Class 'Railt\Compiler\Parser\Runtime' not found in /.../vendor/railt/sdl/src/Parser/SchemaParser.php on line 18
Call Stack
#	Time	Memory	Function	Location
1	0.0023	396472	{main}( )	.../index.php:0
2	0.0313	712448	Railt\Foundation\Application->request( )	.../index.php:51
3	0.0313	712448	Railt\Foundation\Extensions\Repository->boot( )	.../Application.php:191
4	0.0313	712824	Railt\Container\Container->call( )	.../Repository.php:66
5	0.0313	712824	Railt\Container\ParamResolver->fromClosure( )	.../Container.php:199
6	0.0313	712936	Railt\Container\ParamResolver->resolve( )	.../ParamResolver.php:42
7	0.0314	713448	Railt\Container\ParamResolver->resolveParameter( )	.../ParamResolver.php:90
8	0.0314	713448	Railt\Container\ParamResolver->get( )	.../ParamResolver.php:109
9	0.0314	713448	Railt\Container\Container->make( )	.../ParamResolver.php:151
10	0.0314	713448	Railt\Container\Container->get( )	.../Container.php:215
11	0.0314	713448	Railt\Container\Container->resolve( )	.../Container.php:107
12	0.0314	713448	Railt\Container\Container->call( )	.../Container.php:181
13	0.0315	713880	Railt\Foundation\Services\CompilerService->Railt\Foundation\Services\{closure}( )	.../Container.php:201
14	0.0335	718456	Railt\SDL\Compiler->__construct( )	.../CompilerService.php:32
15	0.0349	733280	Railt\SDL\Parser\Factory->getParser( )	.../Compiler.php:86
16	0.0349	733280	Railt\SDL\Parser\Factory->createParser( )	.../Factory.php:38
17	0.0349	733280	class_exists ( )	.../Factory.php:61
18	0.0349	733336	spl_autoload_call ( )	.../Factory.php:61
19	0.0349	733392	Composer\Autoload\ClassLoader->loadClass( )	.../Factory.php:61
20	0.0349	733520	Composer\Autoload\includeFile( )	.../ClassLoader.php:322
21	0.0370	736744	include( '/__/vendor/railt/sdl/src/Parser/SchemaParser.php' )	.../ClassLoader.php:444
```

### Steps To Reproduce:
`composer init`
`composer require laravel/framework`
`composer require railt/rail`

then - just try out the example snippet from here https://ru.railt.org/docs/introduction/installation

```bash
use Railt\Io\File;
use Railt\SDL\Compiler;
use Railt\Http\Request;
use Railt\Foundation\Application;
use Railt\Http\Provider\GlobalsProvider;

require __DIR__ . '/vendor/autoload.php';
$app = new Application();
$schema = File::fromPathname(__DIR__ . '/schema.graphqls');
$request = new Request(new GlobalsProvider());

// here execution brakes!
$response = $app->request($schema, $request); 
$response->send();
```

### Expected result:

expected demo

### What happens instead?

stack trace is above

### Question.

maybe I should test out this framework, by requiring each component seprately? and all component version should match?

**Comment by SerafimArts** [comment]
TL:DR: Do not use master)))

The compiler component is stabilized. I plan to finish in a week.

As a solution to the problem, I can suggest add `composer require railt/compiler dev-master#e44dc3117c4f6fedaa3ee9808bc6c2c7cb963b55` This is the commit that does not contain violations.

**Comment by talbergs** [comment]
Awesome, thank you so much. I'll update issue title, so others may find this support if needed.

**Comment by SerafimArts** [comment]
@talbergs sorry for such a long wait. It was hard work on rewriting the kernel (which is not yet complete). But I do not want to take a long time with the release, so that all the new features that I want to implement are being postponed, but now it is better to implement a relatively stable release.

So here. The current build (`"railt/railt": "dev-master#fe78d45c0e7246a535698dc31645fa50d983f18b"`) is functional and fully passes all tests: https://travis-ci.org/railt/railt/jobs/445353024

This is roughly the state of the project, which will be in the first stable release.
