### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by ggubko** [railt/railt#174]
Quick start is out of date

### Environment

- Railt Version: dev-master
- PHP Version: 7.1

**Comment by SerafimArts** [comment]
1) Fixed readme: https://github.com/railt/railt/commit/26be8e9dd0921118361f4ddd4e226282d2443b53
2) Fixed ru documentation page: https://github.com/railt/docs/commit/566a6ba9510e2bbcc35d7b9a7efaeae7e9af639d
3) Added information about auto-configuration into ru installation page: https://github.com/railt/docs/commit/a9365ce3cfc82d9ae7becb1a40aa38c4da5f1a4c
