### ISSUE TITLE
Railt Compiler 1.3 regression

### ISSUE THREAD

**Issue by sandermarechal** [railt/railt#177]
railt/compiler 1.3 seems to have a regression that does not allow me to read some pp2 files.

### Expected Behavior

The following is my pp2 file. It parses correctly under railt/compiler 1.2.1:

```
// MijnArchief Query Language definition

%skip space \s+

// Scalars
%token true     TRUE|true
%token false    FALSE|false
%token null     NULL|null
%token date     (\d{4}-\d{2}-\d{2})(?:T(\d{2}:\d{2}))?
%token number   \d+
%token dstring  "([^"]*)"
%token sstring  '([^']*)'

// Comparisons
%token eq   =
%token neq  !=
%token gt   >
%token lt   <
%token gte  >=
%token lte  <=

// Logic
%token and     AND|and
%token or      OR|or
%token not     NOT|not

// Grouping
%token brace_  \(
%token _brace  \)

// Fields
%token field    \w+

#conditionalOr -> Prezent\Infrastructure\Query\AST\ConditionalOr:
    conditionalAnd() ( ::or:: conditionalAnd() )*

#conditionalAnd -> Prezent\Infrastructure\Query\AST\ConditionalAnd:
    simpleExpression() ( ::and:: simpleExpression() )*

simpleExpression:
    filter() | negation() | group()

#negation -> Prezent\Infrastructure\Query\AST\Negation:
    ::not:: simpleExpression()

group:
    ::brace_:: conditionalOr() ::_brace::

#filter -> Prezent\Infrastructure\Query\AST\Filter:
    <field> comparisonOperator() scalar()

#comparisonOperator -> Prezent\Infrastructure\Query\AST\ComparisonOperator:
    <eq> | <neq> | <gt> | <lt> | <gte> | <lte>

#scalar -> Prezent\Infrastructure\Query\AST\Scalar:
    <true> | <false> | <null> | <date> | <number> | <dstring> | <sstring>
```

### What happens instead?

I get the following exception using railt/compiler 1.3.0:

> Error while Railt\Compiler\Grammar\Delegate\TokenDelegate initialization: Argument 1 passed to Railt\Parser\Ast\Rule::__construct() must be of the type string, object given, called in /opt/www/sites/sander/mijnarchief/vendor/railt/parser/src/Parser/Ast/Builder.php on line 160

### Description

The problem is that my pp2 file uses delegates. In line 160 it calls `new $delegate($rule)`. But, the delegate class extends Railt\Parser\Ast\Rule (as suggested in your documentation) and it's constructor does not work here.

Note that the delegate constructor is not part of the RuleInterface or LeafInterface!

### Steps To Reproduce

Parse the pp2 using railt/compiler 1.3

### Environment

- Railt Version: 1.3
- PHP Version: 7.2

**Comment by SerafimArts** [comment]
1.3 is an intermediate release that was required to synchronize all the old developments, so the old codebase accidentally got there.

**Comment by SerafimArts** [comment]
Fixed https://github.com/railt/compiler/releases/tag/1.3.1

**Comment by sandermarechal** [comment]
Thanks!

**Comment by SerafimArts** [comment]
Please note that there are absolutely no tests for this package, since focused on working with the main components/packages. So I do not give a guarantee that something else does not break backward compatibility )))

**Comment by sandermarechal** [comment]
If that happens, I'll let it know :-)
