### ISSUE TITLE
[DISCUSSION] How to add a new directive or a extension?

### ISSUE THREAD

**Issue by mihazs** [railt/railt#178]
Hello, i'm very excited about this project.

I'm trying to integrate this on phalcon framework, and what i'm trying to do is to create a directive to handle user authorizations. My idea is similar to the solution made to laravel integration, found in this repository [https://github.com/SerafimArts/railt-authorization](url), but this don't solve my problem, because i'm not using laravel. 

I know that the docs are not made yet, but, can you give a example of how to do this? I'm using the 1.3.5 version of railt. Is there a way to just add a directive using directly the Application class? And how the extensions works??

I'm trying to avoid to do that in controller classes because this will be a very repetitive task and it's not a elegant solution.

**Comment by SerafimArts** [comment]
```php
use Railt\Foundation\Extensions\BaseExtension;
use Railt\SDL\Schema\CompilerInterface;
use Railt\Io\File;
use Symfony\Component\EventDispatcher\EventDispatcherInterface;

class MyExampleExtension extends BaseExtension
{
    public function boot(CompilerInterface $compiler, EventDispatcherInterface $events): void
    {
        // Adding directives inside the application
        $compiler->compile(File::fromSources('directive @example on ...')); 

        // Add listeners
        $events->addListener(TypeBuilding::class, function (TypeBuilding $event) {
            var_dump($event->getType());
        });
    }
}

// Register an extension
$app->extend(MyExampleExtension::class);
```

1) A list of all events is located here https://github.com/railt/railt/tree/1.3.x/src/Foundation/Events
2) An DI is available in the `boot` method. Those... there you can specify any dependencies that are in the container.

**Comment by mihazs** [comment]
I've tested and nothing works.
Here is mu extension class:

`<?php
namespace App\Lib;

use \Railt\Foundation\Events\TypeBuilding;
use \Railt\Foundation\Extensions\BaseExtension;
use \Railt\Io\File;
use \Railt\Reflection\Contracts\Dependent\FieldDefinition;
use \Railt\SDL\Schema\CompilerInterface;
use \Symfony\Component\EventDispatcher\EventDispatcherInterface;

class AuthorizationDirectives extends BaseExtension
{
    public function boot(CompilerInterface $compiler, EventDispatcherInterface $events)
    {   
        
        // Adding directives inside the application
        $compiler->compile(File::fromSources('directive @can(role: String!) on FIELD_DEFINITION')); 
    
        // Add listeners
        $events->addListener(TypeBuilding::class, function (TypeBuilding $event) {
            
            $field = $event->getType();
           // echo "\n----------------------\n";
            //var_dump(get_class($field)); 
            //echo "\n----------------------\n";
            
            if ($field instanceof FieldDefinition && ! $this->allowed($field)) {
                var_dump(get_class($field)); 
                $event->stopPropagation();
            }
        });
    }
    private function allowed(FieldDefinition $field): bool
    {
        foreach ($field->getDirectives('can') as $gate) {
            if (! $this->hasRole($gate->getPassedArgument('role'), $field)) {
               var_dump($gate->getPassedArgument('role'));
              
            }
        }
        return false;
    }
    private function hasRole(string $role, FieldDefinition $field): bool
    {
        return true;
    }
}

`
and here is my test class:

`<?php
namespace Test;

use \App\Lib\ClassScanner;
use \Railt\Io\File;
use \Railt\SDL\Compiler;
use \Railt\Http\Request;
use \Railt\Http\Query;
use \Railt\Foundation\Application;
use \Railt\Routing\RouterExtension;
use \App\Lib\AuthorizationDirectives;
use \App\Graphql\Controllers\Controller;


/**
 * Class GraphQLTest
 */
class GraphQLTest extends \UnitTestCase 
{
    /**
     * @test
     *
     */
    public function testSimpleRequest()
    {
        $schema = File::fromSources('
            schema {
                query: Query
            } 
            
            type Query { 
                scalar(value: String = null): String
                    @can(role: "Pudim") 
                    @route(action: "App\\\\Graphql\\\\Controllers\\\\Controller@scalar") 
                scalar2: String @can(role: "Pudim") 
                 
            }
        ');
        $app = new Application();
        $app->extend(AuthorizationDirectives::class);
        $response = $app->request($schema, new Request(new Query('{ scalar }')));
//        $this->assertSame([], $response->getMessages());
        $this->assertSame(['scalar' => 'default'], $response->getData());
        $response = $app->request($schema, new Request(new Query('{ scalar2 }')));
        //$response = $app->request($schema, new Request(new Query('{ scalar(value: "Value") }')));
       // $this->assertSame([], $response->getMessages());
       // $this->assertSame(['scalar' => 'Value'], $response->getData());
    }
  
    
    public function buildQuery()
    {
      
        
    }

  

}`

They never execute the var_dump present in 
`if ($field instanceof FieldDefinition && ! $this->allowed($field)) {
                var_dump(get_class($field)); 
                $event->stopPropagation();
            }`

I've tried to change the query and the schema but nothing works. What i'm doing wrong?

**Comment by SerafimArts** [comment]
It seems to be working. Very strange.

I will try to check this code by myself a bit later.

**Comment by SerafimArts** [comment]
@mihazs try to change namespace `use \Railt\Reflection\Contracts\Dependent\FieldDefinition;` to `use Railt\SDL\Contracts\Dependent\FieldDefinition;`. 

Package Reflection is temporary frozen. I'm doing his refactoring and maybe I'll return it later. And all his changes are poured into the SDL package.

Before:
![image](https://user-images.githubusercontent.com/2461257/51478310-2ab32d00-1d9c-11e9-87ea-86b2a2122cc5.png)

After:
![image](https://user-images.githubusercontent.com/2461257/51478376-533b2700-1d9c-11e9-877f-be0b7d2f6dd5.png)

**Comment by mihazs** [comment]
Hello, i've tried and i'ts worked, thanks. Can add a docs based in this thread?? It will be very useful.

And, one more question, how can i handle errors? I want to throw an error when the user doesn't have the specified role.

**Comment by SerafimArts** [comment]
> Hello, i've tried and works! Thanks. Can you add a docs based in this thread?? It will be very useful.

There are some minor problems:

1) I write documentation on the basis of the functionality that is stable, well written and will not change significantly in the future. Specifically, this functionality has already been partially rewritten, the events are restructured and renamed. So in the future it is necessary to fix it.
2) That documentation that is written in my native language (RU) so that I can complete and rewrite it faster and more efficiently, until everything stabilizes completely.
3) Stable release 1.3 is a preliminary version so that you can simply try and understand what ideas were incorporated into the concept.

Therefore, I do not know whether it is worth spending time on it, because anyway, this functionality in the current master (1.4.x-dev) branch is no longer there and it has been rewritten.

> And, one more question, how can i handle errors? I want to throw an error when the user doesn't have the specified role.

*1.3.x*
```
use Railt\Foundation\Extensions\BaseExtension;
use  Railt\Http\ResponseInterface;
use  Railt\Http\RequestInterface;

class AuthExtension extends BaseExtension
{
    public function handle(RequestInterface $request, \Closure $then): ResponseInterface
    {
        $response = $then($request);

        foreach ($response->getExceptions() as $exception) {
            if ($exception instanceof MyException) {
                // $exception->makePublic();
            }
        }

        return $response;
    }
}
```

*1.4.x-dev*
```
use Railt\Foundation\Extension\Extension;
use Railt\Foundation\Event\Http\ResponseProceed;

class AuthExtension extends Extension
{
    public function boot(): void
    {
        $this->on(ResponseProceed::class, function (ResponseProceed $event) {
            $response = $event->getResponse();
            var_dump($response->getExceptions());
        });
    }
}
```

**Comment by mihazs** [comment]
Ok, thanks, with this last example i was able to update my code to the version 1.4 of the railt, it's more clearer to me now. I have some other questions, but i will open a new issue for that, it's better for organize and to optimize the search.
