### ISSUE TITLE
[Question] Access parent attributes from route

### ISSUE THREAD

**Issue by mihazs** [railt/railt#179]
I want to use the route directive to solve custom type fields, using the root type, for example: 

```graphql
type Query{
 usuario: [Usuario]
   @route(action: "UserController@list")
}


type Role {
    _key: ID!
    nome: String
}

type User {
    _key: ID!
    nome: String
    login: String
    email: String
    role: Role  
        @route(action: "RoleController@roleByUserId")
}
```
and
```php
class RoleController{
 public function roleByUserId($parent){ //argument $parent can access all the parent data
  $userId = $parent['_key']

  //return the role of the user
 }
}
```
In other words, i want a way to pass a parameter to the controller, and his value will be the same as the field of the type in which the @route directive is declared.

This will be very useful, because we don't need to solve the type "Role" each time that the type "User" are used, for example.

In webonyx we have something like this:
```php
<?php
use GraphQL\Type\Definition\ObjectType;
use GraphQL\Type\Definition\Type;
$queryType = new ObjectType([
    'name' => 'Query',
    'fields' => [
        'echo' => [
            'type' => Type::string(),
            'args' => [
                'message' => Type::nonNull(Type::string()),
            ],
            'resolve' => function ($root, $args) {
                return $root['prefix'] . $args['message'];
            }
        ],
    ],
]);
```
The key of the question is that part:
```php
'resolve' => function ($root, $args) {
                return $root['prefix'] . $args['message'];
            }
```
the $root variable, this is what a want.

It's there a way to do that, maybe using extensions??

**Comment by SerafimArts** [comment]
3) You can use [`Input` object](https://github.com/railt/railt/blob/1.3.x/src/Http/InputInterface.php) for taking info about parent values. It is already inject automatically in each action method (https://github.com/railt/railt/blob/1.3.x/src/Routing/RouterExtension.php#L80-L84).
```
class RoleController
{
    public function roleByUserId(InputInterface $input)
    {
        // $input->getParent(); or  $input->getParentResponse();
    }
}
```

**Comment by mihazs** [comment]
Thanks, for the main propouse the InputInterface works like a charm.
I've tried to use that tip:
```php
public function boot()
{
    $this->register(SomeClass::class, function() {
        return new SomeClass();
    });
}
```

But no success, i'm using the version 1.4.x. How can i do that in 1.4.x, i want to inject like this:
```php
 $this->on(ActionDispatch::class, function (ActionDispatch $event) {

            $action = \explode("@", $event->getAction(), 2);

            if (!$this->actionAllowed($action[0], $action[1])) {
                $event->withAction(function () {
                    throw new UnauthorizedException();
                });
            }
            $di = Di::getDefault();
            $identity = $di->get("session")->get("identity");
            $role = Role::findOneById($identity["data"]["role"]);
            $user = Usuario::findOneById($identity["data"]["user"]);
            $self = $this->actionIsSelf($action[0], $action[1]);

//using this
           // $event->withArgument("authorization", new AuthorizationData($user, $role, $self));
//or this
$this->register(AuthorizationData::class, function() {
        return  new AuthorizationData($user, $role, $self);
    });
        });
```

to use like this:
```php
class RoleController
{
    public function roleByUserId(InputInterface $input, AutorizationData $authorization)
    {
        // $input->getParent(); or  $input->getParentResponse();
    }
}
```
But i'm not able to do that, they can't resolve the $authorization param.

How can i do that?

**Comment by SerafimArts** [comment]
Such code is reproduced in me correctly, maybe you made a logical error somewhere?

**Comment by mihazs** [comment]
Isn't, when i try, this exception are throwed:
![image](https://user-images.githubusercontent.com/3963793/52916746-3c67f180-32c2-11e9-9bbc-dd55d2577266.png)
My class prototype are:
```php
class AuthorizationExtension extends \Railt\Foundation\Extension\Extension
```

If i go to the Railt\Foundation\Extension\Extension, i can see that the only method that can register something are:
```php
    /**
     * @param string $name
     * @param \Closure $registrar
     * @return Extension|$this
     * @throws ContainerInvocationException
     */
    protected function registerIfNotRegistered(string $name, \Closure $registrar): self
    {
        if (! $this->app->has($name) && $instance = $this->app->call($registrar)) {
            $this->app->instance($name, $instance);

            if ($name !== \get_class($instance)) {
                $this->app->alias($name, \get_class($instance));
            }
        }

        return $this;
    }
```
there is no implementation or a declaration of the method register in the class extension.
And if a use the method registerIfNotRegistered, the result works. I don't know if this was expected by you, or if this is a bug, but is nice to give you some feedback. My experience with Railt had been very good.

I'll test the performance and the overhead later, thanks.

**Comment by SerafimArts** [comment]
> there is no implementation or a declaration of the method register in the class extension.

Yes, that's right, I deleted this method so that in the future it would be possible to refactor the container. You can use `$this->app->register` instead.

> My experience with Railt had been very good.

It is very unexpected to hear this, given the strong instability of the functional. But thank you =)

> I'll test the performance and the overhead later, thanks.

Dont worry much about this. For example, this example http://server.railt.org:8081/ maintains 1700+ RPS (You can test it yourself).

VPS:
RAM: 512MB
CPU: 1 Core, 1 Ghz

**Comment by mihazs** [comment]
Works fine, thank you very much.
