### ISSUE TITLE
Return of controller as a list of objects instead list of arrays

### ISSUE THREAD

**Issue by mihazs** [railt/railt#181]
Hello. 
When a field are resolved by the controller, and the field type is a list, the result must to be a list of arrays, otherwise, if I return a list of objects (that can be accessible by using array annotation, because in my try I've implemented the arrayaccess interface), the values of the fields in the response are null, Railt don't resolve correctly. 

For example: 
```php
class UserController{
 public function listAll() {
  $users = Users::findAll(); //returns a list of Users object that implement ArrayAccess interface and extends the Model class
  $r = [] 
  foreach($users as $u) {
   $r["name"] = $u["name"];
   $r["login"] = $u["login"];
  } 
  return $r
 } 

} 
```
This works, but if I try to return the users directly like this 

```php
class UserController{
 public function listAll() {
  $users = Users::findAll(); //returns a list of Users object that implement ArrayAccess interface and extends the Model class
  
  return $users
 } 

} 
```
The result is something like this (it's just a example, ignore the json malformed) :

```json
{
 user:{
   "name": null
    "login": null
 }, {
   "name": null
    "login": null
 }, {
   "name": null
    "login": null
 }, 

} 
```

A list of null field values. 

Is there a way to tell Railt how to properly resolve that? Or, can I make railt able to handle with custom objects in results? 
Railt: 1.4.x

**Comment by greabock** [comment]
I think in future Railt should be able to detect "arrayable" and transform it automaticaly. But right now you have to transform collection of your entities explicitly:
```php
return User::all()->map(function(User $user){
    return $user->toArray();
});
```
This is partly due to the fact that we use webonyx for query execution.

**Comment by SerafimArts** [comment]
> Railt: 1.4.x

This is a bug. I know about this problem of normalization and I came across it myself

**Comment by SerafimArts** [comment]
Fixed: https://github.com/railt/railt/commit/b3e4d836a3d6a46e2588439e6df807e2724a34b5
Tests: https://github.com/railt/railt/blob/b3e4d836a3d6a46e2588439e6df807e2724a34b5/tests/Foundation/Responses/ObjectResponsesTestCase.php#L157-L173
