### ISSUE TITLE
Multiple graphql files and schema extender modularization feature

### ISSUE THREAD

**Issue by mihazs** [railt/railt#182]
Is possible to add a feature that i can write multiple graphql files and combine than in a one?

Example:

UserSchema.graphqls
```graphql
type Query{
   users: User[]
}
type User{
  name: String
  login: String
  email: String
  role: Role
}
```

RoleSchema.graphqls
```graphql
type Query{
   roles: Role[]
}
type Role{
  name: String
  level: Int
}
```

And the root schema:
schema.graphqls
```graphql
schema{
   query: Query
}
```

The result schema should be:
```graphql
schema{
   query: Query
}
type Query{
   roles: Role[]
   users: User[]
}
type User{
  name: String
  login: String
  email: String
  role: Role
}
type Role{
  name: String
  level: Int
}
```
Or, maybe using directives:
```graphql
schema{
   query: Query
}
@import(schema: "UserSchema.graphqls")
@import(schema: "RoleSchema.graphqls")
```

In this webonyx issue [https://github.com/webonyx/graphql-php/issues/180#issuecomment-444478026](url) there are something like that, maybe is a way to start.

This will be nice for a huge number of types and queries.

Thanks.

**Comment by SerafimArts** [comment]
You can use autoloading for this. You should take an instance of compiler from the container and call the autoload method.

```php
$compiler->autoload(function (string $name, TypeDefinition $calledFrom = null) {
    $file = __DIR__ . '/somedir/' . $name . '.graphqls';

    if (\is_file($file)) {
        return File::fromPathname($file);
    }
});
```

Now I am working on the stabilization of the autoload definition functional with `composer.json`. Maybe finish this week, then it will be:

// composer.json
```json
"extra": {
    "railt": {
        "autoload": {
            "paths": ["/path/to/sources/"]
        }
    }
}
```

This functionality already works, but is not stable (it does not always correctly determine relative paths).

JSON Schema look like this: https://github.com/railt/railt/blob/1.4.x/resources/railt.schema.json5#L34-L71

**Comment by mihazs** [comment]
Great, but autoloading will merge the schemas itself and create the bigone?
The autoloading isn't a problem, but, if the compiler will merge the query types in the files and parse like as a unique query (or something like that).
If it is already possible, it was great 👍

**Comment by SerafimArts** [comment]
Autoloading is a way of splitting one schema file into several different physical files. This callback is triggered when there is a lack of some type, interface, scalar, or something else for correct circuit assembly. The first argument is the name of the type being searched. As a second, the type (partially compiled), from where the search was made.

And no, there is nothing "clever" there (for the time being). In case of name conflicts, a name conflict error will occur (magic!).

So in this case, the problem can be solved as follows (like this):

```graphql
// schema.graphqls
schema {
    query: Query
}

type Query {}

// roles-extension.graphqls
extend type Query {
   roles: [Role]
}

// Role.graphqls
type Role { ... }

// users-extension.graphqls
extend type Query {
   users: [User]
}

// User.graphqls
type User {}
```

PHP
```
// In this case, we add the "extension", which will 
// require the Role type, then the autoload will work, which
// will add this same file.
$compiler->compile(File::fromPathname('/example/path/to/roles-extension.graphqls'));

// same with User.graphqls
$compiler->compile(File::fromPathname('/example/path/to/users-extension.graphqls'));
```

**Comment by SerafimArts** [comment]
I finished the implementation of this functionality https://github.com/railt/railt/commit/fa7e245028de76251166f30042715574f3eb6744

Now you can extend schema

```graphqls
# example.graphqls
extend type Query {
   users: [User]
}

type User { ... }
```

Using {{composer.json}}:

```json
{
    "extra": {
        "railt": {
            "preload": {
                "files": [
                    "${app.dir}/path/to/example.graphqls"
                ]
            }
        }
    }
}
```

Or manually:
```php
$compiler->compile(File::fromPathname(__DIR__ . '/.../example.graphqls'));
```

**Comment by mihazs** [comment]
I've tried to do that, and the autoload are never called, even with composer .json correctly configured.
I make an extension to make sure about it, and the autoload closure wasn't called.
```php
class MultipleSchemaExtension extends Extension
{
    public function boot(): void
    {
        $compiler = $this->app->get(CompilerInterface::class);
        $compiler->autoload(function (string $name, TypeDefinition $calledFrom = null) {
            $file = __DIR__ . '/../resources/include/' . strtolower($name) . '.graphqls';

            if (\is_file($file)) {
                return File::fromPathname($file);
            }
        });
    }
}
```

the exception are throwed:
```
Uncaught GraphQL\Error\Error: Cannot query field "usuario" on type "Query". in /app/vendor/webonyx/graphql-php/src/Validator/Rules/FieldsOnCorrectType.php on line 56
```

**Comment by SerafimArts** [comment]
@mihazs The issue is resolved?

**Comment by mihazs** [comment]
@SerafimArts Yes, we resolved that in discord. Thanks
