### ISSUE TITLE
plelase update railt/discovery  to support composer2

### ISSUE THREAD

**Issue by vidyli** [railt/railt#195]
I am using composer2, I got this error when run `compose require railt/rait`

`    - railt/discovery 1.3.0 requires composer-plugin-api ^1.1 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
`

**Comment by SerafimArts** [comment]
Done https://github.com/railt/discovery/commit/088116cd6ec4fc581d99c88ba3746c6401f201a4
