### ISSUE TITLE
The type must include the NotNull modifier when it is extended

### ISSUE THREAD

**Issue by stenin-nikita** [railt/railt#31]
- Railt Version: dev-master
- PHP Version: 7.1
- Component: Reflection

### Description:

The type must include the NotNull modifier when it is extended

### Steps To Reproduce:

```elm
type Some {
    id: String
}

extend type Some {
    id: ID!
}
```

### Expected result:
```elm
type Some {
    id: ID!
}
```

### What happens instead?

```elm
type Some {
    id: ID
}
```

**Comment by SerafimArts** [comment]
Tests: https://github.com/railt/railt/commit/9d7dcea3c219ecf9cb795a4c6fd151f90fec0929

**Comment by SerafimArts** [comment]
Fixed:
1) https://github.com/railt/railt/commit/87ec0f042a403614cab2771944058b0645369550
2) https://github.com/railt/railt/commit/b47e5603680f97bc2df2df673fcdaa112959a8b2
