### ISSUE TITLE
Type collation does not work with directive invocation

### ISSUE THREAD

**Issue by greabock** [railt/railt#86]
- Compiler Version: 1.1.1
- PHP Version: 7.1
- Component: SDL

### Description:
Type collation does not work with directive invocation. Directive argument typing has no affect on directive argument invocation.

### Steps To Reproduce:

Try to compile:
```elm
directive @some(value: [Bar!]!) on OBJECT

input Bar {
   one: String!
   two: String
}

type Foo @some(value: "String is not [Bar!]!"){
    any: String!
}
```
### Expected result:
Compile time exception on directive argument type collation.

### What happens instead?
Compiled successfully and string `String is not [Bar!]!` is actualy value of passed argument

**Comment by SerafimArts** [comment]
Fixed: https://github.com/railt/railt/commit/d8df098de442d70205f2db4f48d457949f00b2a1

Fixes will be in the next release.
